project:
  type: website
  resources:
    - tree-of-life/*
    - data/*
    - imgs/*
    - tiles_v2.html


website:
  title: "Urban Taxonomy"
  site-url: https://urbantaxonomy.org
  twitter-card:
    title: Urban Taxonomy using Hierarchical Morphotope Classification
    description: A classification of built-up fabric. It divides cities into regions of consistent patterns of urban form and connects them via a taxonomic tree.
    image: imgs/preview.jpg
  open-graph:
    title: Urban Taxonomy using Hierarchical Morphotope Classification
    description: A classification of built-up fabric. It divides cities into regions of consistent patterns of urban form and connects them via a taxonomic tree.
    image: imgs/preview.jpg
  navbar:
    background: white
    foreground: '#222222'
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: map.qmd
        text: Map
      - data.qmd
      - docs.ipynb
      - href: https://doi.org/10.48550/arXiv.2509.10083
        text: Paper
        target: _blank
    right:
      - href: data.qmd
        text: DATA DOWNLOAD {{< fa arrow-right >}}
  repo-url: "https://github.com/uscuni/himoc"
  page-footer:
    center:
      - text: "Copyright 2025, Charles University"
    right:
      - icon: github
        href: "https://github.com/uscuni/himoc"
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



