[project]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "himoc"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
flask = ">=3.1.0,<4"
pmtiles = ">=3.4.1,<4"
